### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by setop** [jbruchon/jodyhash#1]
Hi,

When I compare jodyhash and xxHash64 on my machine, it does not confirm the figures given on the jodyhash project page.

```
 dd if=/dev/shm/sample.bin bs=32768 | ./xxHash/xxh64sum
131072+0 records in
131072+0 records out
489f523e1b4477cd  -
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 1.1282 s, 3.8 GB/s

dd if=/dev/shm/sample.bin bs=32768 | ./jodyhash/jodyhash 
131072+0 records in
131072+0 records out
6d8fb18010b97cf6
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 1.97783 s, 2.2 GB/s
```
xxh64sum seems twice as fast as jodyhash.

What can explain the difference ?

**Comment by jbruchon** [comment]
I have my `shm` set to a lower limit, but I just `git clone`d, built, and ran the same test with a 2GB file and the latest versions of `xxhsum` (0.6.3, 64-bit hash selected) and `jodyhash` and I don't get the results you get:
```
$ dd if=/dev/shm/sample.bin bs=32768 | ./xxhsum -H1 >/dev/null 2>/dev/null
65536+0 records in
65536+0 records out
2147483648 bytes (2.1 GB) copied, 1.41832 s, 1.5 GB/s
$ dd if=/dev/shm/sample.bin bs=32768 | ./jodyhash >/dev/null 2>/dev/null
65536+0 records in
65536+0 records out
2147483648 bytes (2.1 GB) copied, 1.3061 s, 1.6 GB/s
```
This is on a Phenom II X6 1035T with the `performance` cpufreq governor, compiled with GCC 7.2.0 and with an idle CPU otherwise.

**Comment by jbruchon** [comment]
Based on cachegrind teseting I've run, xxHash64 will theoretically perform its hashing in 3/5 the time of jodyhash. If you pass the file to hash directly to either then the `xxhsum` utility using xxHash64 runs 10% faster than `jodyhash` with 64-bit width. Passing in 32K chunks with `dd` works faster for `jodyhash` on my machine, possibly due to the utility being tuned for and tested on that exact machine all the time.

After doing some more testing, I'm going to see if I can improve the theoretical performance of the algorithm further.

**Comment by setop** [comment]
Thanks for your analysis.
BTW, I use a Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz. But and old GCC 5.4.0

**Comment by jbruchon** [comment]
When I tried it with both `cat file | ./hashprogram` and `./hashprogram file` the xxHash64 time was quicker. There could be several differences between systems that make `dd bs=32768` vary between systems; anything from which package and version provides `dd` to how `memcpy()` is implemented in the C library and for that particular CPU. It's also possible that CPU speed variances like Intel Turbo Boost or throttling could be affecting the results (though not on mine since it's locked to the highest speed and doesn't have Turbo anything). In cachegrind I noticed that `jodyhash` has a lot less L1 D-cache misses than `xxhsum -H1` but executes over 3x as many CPU instructions and has double the count of L1 D-cache references.

I don't think the version of GCC matters that much in this case; jodyhash was made specifically to easily compile directly into specific CPU instructions and it seems xxHash is similar (GCC 7 is unlikely to optimize a bitwise rotate, XOR, add, or multiply any better than GCC 5).

I'm testing some variants on my algorithm for performance and I'll expand my final tests to some of the other platforms I have available to get a more accurate picture of what's going on.

**Comment by setop** [comment]
You're right. I was using dd by laziness because is report bandwidth.
But if I use <cmd> <file>, it is notably faster.

```
time ./jodyhash/jodyhash /dev/shm/sample.bin 
f081d10bae04d0de
real 0m1.713s ; user 0m1.286s ; sys 0m0.427s

time ./xxHash/xxh64sum /dev/shm/sample.bin 
becd143c5c0cfb54  /dev/shm/sample.bin
real 0m0.718s ; user 0m0.307s ; sys 0m0.410s
```

**Comment by jbruchon** [comment]
That looks about right. My hash executes more operations so it should be slower. Those figures look roughly like the difference I saw.
